# Generated by Django 5.2 on 2025-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_billing_address_payment_cart_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cod_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When COD order was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cod_notes',
            field=models.TextField(blank=True, help_text='Special notes for COD delivery', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay (Online)'), ('cod', 'Cash on Delivery')], default='razorpay', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cod_confirmed', 'COD Confirmed')], default='pending', max_length=20),
        ),
    ]
