# Generated by Django 5.2 on 2025-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_cod_confirmed_at_payment_cod_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pathlog_transaction_id',
            field=models.CharField(blank=True, help_text='Pathlog wallet transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pathlog_verified_at',
            field=models.DateTimeField(blank=True, help_text='When wallet was verified', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pathlog_wallet_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Available wallet balance', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pathlog_wallet_mobile',
            field=models.CharField(blank=True, help_text='Registered mobile number for Pathlog Wallet', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pathlog_wallet_otp',
            field=models.CharField(blank=True, help_text='OTP for wallet verification', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pathlog_wallet_verified',
            field=models.BooleanField(default=False, help_text='Whether wallet is verified'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay (Online)'), ('cod', 'Cash on Delivery'), ('pathlog_wallet', 'Pathlog Wallet')], default='razorpay', max_length=50),
        ),
    ]
