# Generated by Django 5.2 on 2025-04-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_updated_at_productvariant_stock_and_more'),
        ('wishlist', '0003_wishlistitem_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlistitem',
            name='unique_product_variant_in_wishlist',
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('wishlist', 'product'), name='unique_product_in_wishlist'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('wishlist', 'product', 'variant'), name='unique_product_variant_in_wishlist'),
        ),
    ]
