# Generated by Django 5.2 on 2025-06-09 19:44

import coupon.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code for customers to enter', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of the coupon')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage or fixed amount based on coupon_type', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage coupons)', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum cart value required to apply this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicable_to', models.CharField(choices=[('all', 'All Products'), ('pathology', 'Pathology Products Only'), ('doctor', 'Doctor Products Only'), ('medical', 'Medical Products Only')], default='all', help_text='Which product types this coupon applies to', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When the coupon becomes active')),
                ('valid_to', models.DateTimeField(default=coupon.models.default_valid_to, help_text='When the coupon expires')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this coupon can be used')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, help_text='How many times this coupon has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is currently active')),
                ('assigned_to_all', models.BooleanField(default=True, help_text='If True, coupon is available to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Specific users this coupon is assigned to (if not assigned_to_all)', related_name='assigned_coupons', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
                'permissions': [('can_generate_coupons', 'Can generate coupon codes')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupon_coup_code_e43490_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='coupon_coup_valid_f_8bd8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupon_coup_is_acti_5fc9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_type'], name='coupon_coup_coupon__2f40b8_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user', 'applied_at'], name='coupon_coup_user_id_06e3a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'order_id')},
        ),
    ]
