# Generated by Django 5.2 on 2025-04-16 12:17

import coupon.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'permissions': [('can_generate_coupons', 'Can generate coupon codes')], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Products'), ('pathology', 'Pathology Products Only'), ('doctor', 'Doctor Products Only'), ('medical', 'Medical Products Only')], default='all', help_text='Which product types this coupon applies to', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='assigned_to_all',
            field=models.BooleanField(default=True, help_text='If True, coupon is available to all users'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Specific users this coupon is assigned to (if not assigned_to_all)', related_name='assigned_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='Internal description of the coupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage or fixed amount based on coupon_type', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this coupon is currently active'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage coupons)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times this coupon can be used'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum cart value required to apply this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='How many times this coupon has been used'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the coupon becomes active'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=coupon.models.default_valid_to, help_text='When the coupon expires'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Unique coupon code for customers to enter', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupon_coup_code_e43490_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='coupon_coup_valid_f_8bd8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupon_coup_is_acti_5fc9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_type'], name='coupon_coup_coupon__2f40b8_idx'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user', 'applied_at'], name='coupon_coup_user_id_06e3a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'order_id')},
        ),
    ]
