# Generated by Django 5.2 on 2025-06-09 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='products.product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together={('period_type', 'start_date', 'end_date')},
        ),
        migrations.AddField(
            model_name='useractivity',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type'], name='analytics_a_event_t_a460ec_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user'], name='analytics_a_user_id_3326ea_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['created_at'], name='analytics_a_created_546677_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_key'], name='analytics_a_session_598c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product'], name='analytics_p_product_640e99_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user'], name='analytics_p_user_id_c3a7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['created_at'], name='analytics_p_created_6e649d_idx'),
        ),
    ]
