# Generated by Django 5.2 on 2025-11-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_carouselbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselbanner',
            name='image',
            field=models.CharField(help_text='ImageKit URL for carousel banner image (stored as URL, not file)', max_length=500),
        ),
    ]
