# Generated by Django 5.2 on 2025-08-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_line_1_user_address_line_2_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medixmall_mode',
            field=models.BooleanField(default=False, help_text='When enabled, user only sees medicine products (MedixMall mode)'),
        ),
    ]
