# Generated by Django 5.2 on 2025-09-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_duty',
            field=models.BooleanField(default=True, help_text="For suppliers: When OFF, their products won't show in public listings. When ON, products are visible."),
        ),
    ]
