# Generated by Django 5.2 on 2025-09-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_on_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('supplier', 'Supplier'), ('admin', 'Admin'), ('rx_verifier', 'RX Verifier')], default='user', max_length=20),
        ),
    ]
