# Generated by Django 5.2 on 2025-09-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='otp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', False)), fields=('user', 'otp_type'), name='unique_unverified_otp_per_user_type'),
        ),
    ]
