# Generated by Django 5.2 on 2025-09-24 10:45

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_otp_unique_unverified_otp_per_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('email_verify', 'Email Verified'), ('profile_update', 'Profile Updated'), ('address_update', 'Address Updated'), ('role_change', 'Role Changed'), ('account_status_change', 'Account Status Changed'), ('otp_request', 'OTP Requested'), ('otp_verify', 'OTP Verified'), ('supplier_request', 'Supplier Request Submitted'), ('supplier_approved', 'Supplier Request Approved'), ('supplier_rejected', 'Supplier Request Rejected'), ('suspicious_activity', 'Suspicious Activity Detected'), ('data_export', 'Data Export'), ('account_deletion', 'Account Deletion')], max_length=50)),
                ('resource', models.CharField(help_text='Resource being acted upon', max_length=100)),
                ('details', models.JSONField(default=dict, help_text='Additional action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='accounts_au_user_id_96c97d_idx'), models.Index(fields=['timestamp'], name='accounts_au_timesta_276167_idx'), models.Index(fields=['action'], name='accounts_au_action_5ca9a9_idx'), models.Index(fields=['ip_address'], name='accounts_au_ip_addr_8bfa9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('password_hash', models.CharField(help_text='Encrypted password until approval', max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('pan_number', models.CharField(max_length=10)),
                ('business_license', accounts.models.ImageKitField(blank=True, help_text='Business license document', max_length=500, null=True)),
                ('gst_certificate', accounts.models.ImageKitField(blank=True, help_text='GST registration certificate', max_length=500, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('years_in_business', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_turnover', models.CharField(blank=True, max_length=50, null=True)),
                ('product_categories', models.TextField(help_text='Categories of products they want to sell')),
                ('bank_account_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_request', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supplier_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_su_status_9a3627_idx'), models.Index(fields=['requested_at'], name='accounts_su_request_38e732_idx'), models.Index(fields=['gst_number'], name='accounts_su_gst_num_b91603_idx')],
            },
        ),
    ]
