# Generated by Django 5.2 on 2025-09-21 17:59

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor_license', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_clinic', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('prescription_type', models.CharField(choices=[('image', 'Image Upload'), ('pdf', 'PDF Document'), ('camera', 'Camera Capture')], default='image', max_length=20)),
                ('prescription_image', accounts.models.ImageKitField(blank=True, max_length=500, null=True, verbose_name='Prescription Image')),
                ('prescription_file_url', models.URLField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Medical diagnosis from prescription', null=True)),
                ('medications_prescribed', models.TextField(blank=True, help_text='List of prescribed medications', null=True)),
                ('dosage_instructions', models.TextField(blank=True, help_text='Dosage and usage instructions', null=True)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('prescription_valid_until', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('clarification_needed', 'Clarification Needed')], default='pending', max_length=25)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from verifier', null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Additional notes from customer', null=True)),
                ('clarification_requested', models.TextField(blank=True, help_text='Clarification requested from customer', null=True)),
                ('customer_response', models.TextField(blank=True, help_text='Customer response to clarification', null=True)),
                ('image_quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Image quality score (0-10)', max_digits=3, null=True)),
                ('legibility_score', models.DecimalField(blank=True, decimal_places=2, help_text='Text legibility score (0-10)', max_digits=3, null=True)),
                ('completeness_score', models.DecimalField(blank=True, decimal_places=2, help_text='Information completeness score (0-10)', max_digits=3, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent for priority verification')),
                ('priority_level', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=3, help_text='Verification priority level')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_uploads', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'rx_verifier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='rx_upload.prescriptionupload')),
            ],
            options={
                'ordering': ['medication_name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Prescription Created'), ('assigned', 'Assigned to Verifier'), ('reviewed', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('clarification_requested', 'Clarification Requested'), ('clarification_received', 'Clarification Received'), ('notes_updated', 'Notes Updated')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rx_upload.prescriptionupload')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VerifierWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('in_review_count', models.PositiveIntegerField(default=0)),
                ('total_verified', models.PositiveIntegerField(default=0)),
                ('total_approved', models.PositiveIntegerField(default=0)),
                ('total_rejected', models.PositiveIntegerField(default=0)),
                ('average_processing_time', models.DecimalField(decimal_places=2, default=0.0, help_text='In hours', max_digits=5)),
                ('accuracy_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Accuracy percentage', max_digits=3)),
                ('customer_satisfaction', models.DecimalField(decimal_places=2, default=0.0, help_text='Satisfaction score', max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('max_daily_capacity', models.PositiveIntegerField(default=50, help_text='Maximum prescriptions per day')),
                ('current_daily_count', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('verifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workload_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verifier Workload',
                'verbose_name_plural': 'Verifier Workloads',
            },
        ),
        migrations.AddIndex(
            model_name='prescriptionupload',
            index=models.Index(fields=['verification_status'], name='rx_upload_p_verific_9aa04e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionupload',
            index=models.Index(fields=['uploaded_at'], name='rx_upload_p_uploade_648b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionupload',
            index=models.Index(fields=['customer'], name='rx_upload_p_custome_ddaf6e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionupload',
            index=models.Index(fields=['verified_by'], name='rx_upload_p_verifie_dc9715_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionupload',
            index=models.Index(fields=['is_urgent', '-uploaded_at'], name='rx_upload_p_is_urge_74f988_idx'),
        ),
    ]
