# Generated by Django 5.2 on 2025-09-21 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, help_text='Medical specialization (e.g., General Medicine, Cardiology)', max_length=100, null=True)),
                ('license_number', models.CharField(help_text='Medical license number', max_length=50, unique=True)),
                ('verification_level', models.CharField(choices=[('junior', 'Junior Verifier'), ('senior', 'Senior Verifier'), ('specialist', 'Specialist Verifier'), ('supervisor', 'Supervisor')], default='junior', max_length=20)),
                ('max_daily_prescriptions', models.PositiveIntegerField(default=50, help_text='Maximum prescriptions per day')),
                ('is_available', models.BooleanField(default=True, help_text='Available for new assignments')),
                ('performance_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall performance rating (0-10)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verifier Profile',
                'verbose_name_plural': 'Verifier Profiles',
            },
        ),
    ]
