# Generated by Django 5.2 on 2025-11-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_upload', '0002_verifierprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionupload',
            name='patient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
