# Generated by Django 5.2 on 2025-08-28 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shiprocket_shipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('awb_code', models.CharField(blank=True, max_length=100, null=True)),
                ('courier_company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_location', models.CharField(default='Primary', max_length=100)),
                ('pickup_address', models.TextField()),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_pincode', models.CharField(max_length=10)),
                ('delivery_country', models.CharField(default='India', max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Prepaid', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('pickup_generated', 'Pickup Generated'), ('manifested', 'Manifested'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='pending', max_length=50)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('items_data', models.JSONField(default=list)),
                ('tracking_data', models.JSONField(default=dict)),
                ('shiprocket_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_order_id', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Delivered'), ('size_issue', 'Size Issue'), ('quality_issue', 'Quality Issue'), ('not_needed', 'No Longer Needed'), ('damaged', 'Damaged in Transit'), ('other', 'Other')], max_length=50)),
                ('reason_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered_to_origin', 'Delivered to Origin'), ('cancelled', 'Cancelled')], default='initiated', max_length=50)),
                ('return_awb', models.CharField(blank=True, max_length=100, null=True)),
                ('return_pickup_date', models.DateField(blank=True, null=True)),
                ('return_tracking_data', models.JSONField(default=dict)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_refund_processed', models.BooleanField(default=False)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='requested', max_length=50)),
                ('pickup_boy_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_boy_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('comments', models.TextField(blank=True)),
                ('shiprocket_pickup_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_request', to='shipping.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('source', models.CharField(default='shiprocket', max_length=50)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(max_length=100)),
                ('courier_id', models.CharField(max_length=50)),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('delivery_pincode', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('freight_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.CharField(blank=True, max_length=50)),
                ('is_cod_available', models.BooleanField(default=False)),
                ('is_prepaid_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingprovider')),
            ],
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order_id'], name='shipping_sh_order_i_cb7c84_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['awb_code'], name='shipping_sh_awb_cod_6606a7_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipping_sh_status_0644c6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['delivery_pincode'], name='shipping_sh_deliver_345c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingevent',
            index=models.Index(fields=['shipment', 'event_time'], name='shipping_sh_shipmen_8098a0_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingevent',
            index=models.Index(fields=['status'], name='shipping_sh_status_80d140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('courier_id', 'pickup_pincode', 'delivery_pincode', 'weight')},
        ),
    ]
