# Generated by Django 5.2 on 2025-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('equipment', 'Doctor Equipment'), ('pathology', 'Pathology Product')], default='medicine', max_length=20),
        ),
    ]
