# Generated by Django 5.2 on 2025-06-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productauditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='supplierproductprice',
            name='products_su_product_c439c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierproductprice',
            name='products_su_product_f599e2_idx',
        ),
    ]
