# Generated by Django 5.2 on 2025-04-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-additional_price']},
        ),
    ]
