# Generated by Django 5.2 on 2025-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_brand_approved_at_brand_approved_by_brand_is_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Variant-specific image (e.g., for different colors/sizes)', null=True),
        ),
    ]
